language: node_js
node_js:
  - "8"
before_install:
  - echo "$var" > "$destdir"
install:
  - npm install
  - npm i -g mocha
before_script:
  - npm run-script beautify
script:
  - mocha
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL